<?php

return [
    'migration' => [
        'name_schema' => '{{ date }}_000000_create_{{ table }}_table',
        'name_count' => 'P',
        'family' => 'database',
        'convention' => 'snake',
        'path_schema' => '{{ container }}',
        'tasks' => [''],
        'variations' => ['create', 'update'],
        'pairs' => ['model', 'factory', 'seeder'],
    ],
    'factory' => [
        'name_schema' => '{{ name }}{{ suffix }}',
        'name_count' => 'S',
        'family' => 'database',
        'path_schema' => '{{ container }}',
        'tasks' => [''],
        'variations' => [''],
        'pairs' => [],
    ],
    'seeder' => [
        'name_schema' => '{{ name }}{{ suffix }}',
        'name_count' => 'S',
        'family' => 'database',
        'path_schema' => '{{ container }}',
        'tasks' => [''],
        'variations' => [''],
        'pairs' => [],
    ],
    'test' => [
        'name_schema' => '{{ task }}{{ name }}{{ suffix }}',
        'name_count' => 'S',
        'family' => 'tests',
        'path_schema' => '{{ variation }}{{ folder }}{{ subs }}',
        'tasks' => ['', 'index', 'show', 'create', 'store', 'edit', 'update', 'destroy'],
        'variations' => ['feature', 'unit'],
        'pairs' => [],
    ],
    'action' => [
        'name_schema' => '{{ name }}',
        'name_count' => 'X',
        'family' => 'src',
        'path_schema' => '{{ container }}{{ subs }}',
        'tasks' => [''],
        'variations' => ['', 'static'],
        'pairs' => [],
    ],
    'cast' => [
        'name_schema' => '{{ name }}{{ suffix }}',
        'name_count' => 'S',
        'family' => 'src',
        'path_schema' => '{{ container }}{{ subs }}',
        'tasks' => [''],
        'variations' => [''],
        'pairs' => [],
    ],
    'channel' => [
        'name_schema' => '{{ name }}{{ suffix }}',
        'name_count' => 'S',
        'family' => 'src',
        'path_schema' => '{{ container }}{{ subs }}',
        'tasks' => [''],
        'variations' => [''],
        'pairs' => [],
        'require' => ['model', 'user', ''],
    ],
    'command' => [
        'name_schema' => '{{ name }}{{ suffix }}',
        'name_count' => 'X',
        'family' => 'src',
        'path_schema' => '{{ container }}{{ subs }}',
        'tasks' => [''],
        'variations' => [''],
        'pairs' => [],
    ],
    'component' => [
        'name_schema' => '{{ name }}',
        'name_count' => 'X',
        'family' => 'src',
        'path_schema' => '{{ view }}{{ container }}{{ subs }}',
        'tasks' => [''],
        'variations' => [''],
        'pairs' => [],
    ],
    'controller' => [
        'name_schema' => '{{ name }}{{ suffix }}',
        'name_count' => 'S',
        'family' => 'src',
        'path_schema' => '{{ wrapper }}{{ container }}{{ app }}{{ api }}{{ subs }}',
        'tasks' => [''],
        'variations' => ['', 'api', 'invokable', 'model-api', 'model', 'nested-api', 'nested', 'plain'],
        'pairs' => ['model', 'request', 'resource', 'service'],
    ],
    'enum' => [
        'name_schema' => '{{ name }}',
        'name_count' => 'X',
        'family' => 'src',
        'path_schema' => '{{ container }}{{ subs }}',
        'tasks' => [''],
        'variations' => [''],
        'pairs' => [],
    ],
    'event' => [
        'name_schema' => '{{ name }}',
        'name_count' => 'X',
        'family' => 'src',
        'path_schema' => '{{ container }}{{ subs }}',
        'tasks' => [''],
        'variations' => [''],
        'pairs' => [],
        'require' => ['provider', 'event', 'event'],
    ],
    'exception' => [
        'name_schema' => '{{ name }}{{ suffix }}',
        'name_count' => 'X',
        'family' => 'src',
        'path_schema' => '{{ container }}{{ subs }}',
        'tasks' => [''],
        'variations' => [''],
        'pairs' => [],
    ],
    'interface' => [
        'name_schema' => '{{ name }}',
        'name_count' => 'X',
        'family' => 'src',
        'path_schema' => '{{ container }}{{ subs }}',
        'tasks' => [''],
        'variations' => [''],
        'pairs' => [],
    ],
    'job' => [
        'name_schema' => '{{ name }}{{ suffix }}',
        'name_count' => 'S',
        'family' => 'src',
        'path_schema' => '{{ container }}{{ subs }}',
        'tasks' => [''],
        'variations' => ['', 'queued'],
        'pairs' => [],
    ],
    'listener' => [
        'name_schema' => '{{ name }}{{ suffix }}',
        'name_count' => 'X',
        'family' => 'src',
        'path_schema' => '{{ container }}{{ subs }}',
        'tasks' => [''],
        'variations' => [''],
        'pairs' => [],
    ],
    'mail' => [
        'name_schema' => '{{ name }}{{ suffix }}',
        'name_count' => 'S',
        'family' => 'src',
        'path_schema' => '{{ container }}{{ subs }}',
        'tasks' => [''],
        'variations' => ['', 'markdown'],
        'pairs' => [],
    ],
    'middleware' => [
        'name_schema' => '{{ name }}',
        'name_count' => 'X',
        'family' => 'src',
        'path_schema' => '{{ wrapper }}{{ container }}{{ subs }}',
        'tasks' => [''],
        'variations' => [''],
        'pairs' => [],
    ],
    'model' => [
        'name_schema' => '{{ name }}',
        'name_count' => 'S',
        'family' => 'src',
        'path_schema' => '{{ container }}',
        'tasks' => [''],
        'variations' => ['', 'pivot'],
        'pairs' => ['policy', 'migration'],
    ],
    'notification' => [
        'name_schema' => '{{ name }}{{ suffix }}',
        'name_count' => 'S',
        'family' => 'src',
        'path_schema' => '{{ container }}{{ subs }}',
        'tasks' => [''],
        'variations' => ['', 'markdown'],
        'pairs' => [],
    ],
    'observer' => [
        'name_schema' => '{{ name }}{{ suffix }}',
        'name_count' => 'S',
        'family' => 'src',
        'path_schema' => '{{ container }}{{ subs }}',
        'tasks' => [''],
        'variations' => [''],
        'pairs' => ['model'],
    ],
    'policy' => [
        'name_schema' => '{{ name }}{{ suffix }}',
        'name_count' => 'S',
        'family' => 'src',
        'path_schema' => '{{ container }}',
        'tasks' => [''],
        'variations' => [''],
        'pairs' => ['model'],
        'require' => ['model', 'user', ''],
    ],
    'provider' => [
        'name_schema' => '{{ name }}Service{{ suffix }}',
        'name_count' => 'X',
        'family' => 'src',
        'path_schema' => '{{ container }}',
        'tasks' => [''],
        'variations' => ['', 'event'],
        'pairs' => [],
    ],
    'resource' => [
        'name_schema' => '{{ name }}{{ suffix }}',
        'name_count' => 'S',
        'family' => 'src',
        'path_schema' => '{{ wrapper }}{{ container }}{{ subs }}',
        'tasks' => [''],
        'variations' => ['', 'collection'],
        'pairs' => [],
    ],
    'request' => [
        'name_schema' => '{{ task }}{{ name }}{{ suffix }}',
        'name_count' => 'S',
        'family' => 'src',
        'path_schema' => '{{ wrapper }}{{ container }}{{ folder }}{{ subs }}',
        'tasks' => ['store', 'update'],
        'variations' => [''],
        'pairs' => [],
    ],
    'rule' => [
        'name_schema' => '{{ name }}{{ suffix }}',
        'name_count' => 'S',
        'family' => 'src',
        'path_schema' => '{{ container }}{{ subs }}',
        'tasks' => [''],
        'variations' => ['', 'implicit'],
        'pairs' => [],
    ],
    'service' => [
        'name_schema' => '{{ task }}{{ name }}{{ suffix }}',
        'name_count' => 'S',
        'family' => 'src',
        'path_schema' => '{{ container }}{{ folder }}{{ subs }}',
        'tasks' => ['', 'index', 'show', 'create', 'store', 'edit', 'update', 'destroy'],
        'variations' => [''],
        'pairs' => [],
    ],
    'trait' => [
        'name_schema' => '{{ name }}',
        'name_count' => 'X',
        'family' => 'src',
        'path_schema' => '{{ container }}{{ subs }}',
        'tasks' => [''],
        'variations' => [''],
        'pairs' => [],
    ],
];
